name: gooritabasecode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  form_validator: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.0.2
  jwt_decoder: ^2.0.1

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter: 
  assets: 
    - .env
    - assets/images/
  uses-material-design: true

